### ISSUE TITLE
Unable to initialize main class

### ISSUE THREAD

**Issue by codewithmishra** [frieden84/DemaRQ#1]
Error: Unable to initialize main class lu.svv.saa.requirements.autofinding.pipelines.DemarcateRequirements
Caused by: java.lang.NoClassDefFoundError: org/apache/uima/resource/ResourceInitializationException

The above error is being displayed. Maybe some issues with the source pom.xml

**Comment by frieden84** [comment]
The lib folder was missing, I just uploaded it. Please note that the docx reader uses the free trial of Aspose, which might cause interruptions in case of long MS documents. Also, DKPro has updated its libraries now, so hopefully you won't get any errors, but keep that in mind.
